import { PrismaClient, Role, ApplicationStatus } from "../src/generated/prisma";
import * as bcrypt from "bcrypt"; // Ensure bcrypt is installed: npm install bcrypt

const prisma = new PrismaClient();

async function main() {
  // Clear existing data (order matters due to foreign keys)
  // Delete records in models that depend on others first.
  await prisma.certificate.deleteMany();
  await prisma.project.deleteMany();
  await prisma.application.deleteMany();
  await prisma.talent.deleteMany();
  await prisma.mentor.deleteMany();
  await prisma.department.deleteMany();
  await prisma.user.deleteMany(); // Delete users last as other models depend on it

  console.log("Cleared existing data.");

  // Create Departments
  const departmentsData = [
    {
      name: "Software Development",
      description: "Web, Mobile, and Desktop application development",
    },
    {
      name: "Cybersecurity",
      description: "Network security, ethical hacking, and digital forensics",
    },
    {
      name: "Embedded Systems",
      description: "Hardware-software integration and IoT",
    },
    {
      name: "Aerospace Engineering",
      description: "Spacecraft and aircraft design and development",
    },
  ];

  const departments = await Promise.all(
    departmentsData.map((data) => prisma.department.create({ data }))
  );
  console.log("Created departments.");

  // Create Admin User
  const adminPassword = await bcrypt.hash("admin123", 10);
  const adminUser = await prisma.user.create({
    data: {
      // id will be auto-generated by @default(uuid()) in User model
      name: "Admin User",
      email: "admin@example.com",
      password: adminPassword,
      role: Role.ADMIN,
      phone: "999-999-9999",
      image: "https://example.com/images/admin.jpg",
    },
  });
  console.log("Created admin user.");

  // Create Mentor Users and Mentors (5 mentors, distributed among 4 departments)
  const mentors = [];
  for (let i = 0; i < 5; i++) {
    // Loop 5 times for 5 mentors
    const mentorData = {
      firstName: `Mentor${i + 1}`,
      lastName: `Last${i + 1}`,
      email: `mentor${i + 1}@example.com`,
      phone: `111-222-33${String(i + 1).padStart(2, "0")}`,
      password: "password123",
      departmentName: departmentsData[i % departmentsData.length].name, // Cycle through department names
      maxStudents: 7 - (i % 3), // Vary max students
      sex: i % 2 === 0 ? "Female" : "Male",
      image: `https://example.com/images/mentor${i + 1}.jpg`,
      address: `${100 + i} Mentor Street, City, Country`,
      bloodType: i % 2 === 0 ? "A+" : "O+",
      birthday: new Date(1980 + i, 1, 1), // Sample birthday
    };

    const hashedPassword = await bcrypt.hash(mentorData.password, 10);

    // 1. Create a User record for the mentor
    const user = await prisma.user.create({
      data: {
        // id will be auto-generated by @default(uuid()) in User model
        name: `${mentorData.firstName} ${mentorData.lastName}`,
        email: mentorData.email,
        password: hashedPassword,
        role: Role.MENTOR,
        phone: mentorData.phone,
        image: mentorData.image,
      },
    });

    const department = departments.find(
      (d) => d.name === mentorData.departmentName
    );
    if (!department) {
      throw new Error(`Department ${mentorData.departmentName} not found.`);
    }

    // 2. Create a Mentor record
    const mentor = await prisma.mentor.create({
      data: {
        // id will be auto-generated by @default(uuid()) in Mentor model
        name: mentorData.firstName,
        surname: mentorData.lastName,
        email: mentorData.email,
        password: hashedPassword, // 'password' is now optional, but providing it is fine
        phone: mentorData.phone,
        userId: user.id, // Link to the created User's ID (which is String)
        departmentId: department.id, // Link to Department's ID (which is String)
        maxStudents: mentorData.maxStudents,
        currentStudents: 0,
        sex: mentorData.sex,
        image: mentorData.image,
        address: mentorData.address,
        bloodType: mentorData.bloodType,
        birthday: mentorData.birthday, // Added birthday
      },
    });
    mentors.push(mentor);
  }
  console.log("Created mentor users and mentors.");

  // Create Talent Users and Talents (30 talents)
  const talents = [];
  for (let i = 1; i <= 30; i++) {
    const talentPassword = await bcrypt.hash(`talent${i}password`, 10);

    // 1. Create a User record for the talent
    const user = await prisma.user.create({
      data: {
        // id will be auto-generated by @default(uuid()) in User model
        name: `Talent Name ${i}`,
        email: `talent${i}@example.com`,
        password: talentPassword,
        role: Role.TALENT,
        phone: `123-456-78${String(i).padStart(2, "0")}`,
        image: `https://example.com/images/talent${i}.jpg`,
      },
    });

    // 2. Create a Talent record
    const talent = await prisma.talent.create({
      data: {
        // id will be auto-generated by @default(uuid()) in Talent model
        userId: user.id, // Link to the created User's ID (which is String)
        age: 20 + (i % 10),
        education: i % 2 === 0 ? "Computer Science" : "Software Engineering",
        github: `github.com/talent${user.id}`,
        leetcode: `leetcode.com/talent${user.id}`,
        image: `https://example.com/images/talent_profile_${user.id}.jpg`,
      },
    });
    talents.push(talent);
  }
  console.log("Created talent users and talents.");

  // Create Applications
  for (let i = 0; i < talents.length; i++) {
    const talent = talents[i];
    const department = departments[i % departments.length]; // Distribute talents across 4 departments
    const mentor = mentors[i % mentors.length]; // Assign mentors circularly

    const applicationStatus =
      i % 3 === 0
        ? ApplicationStatus.ACCEPTED
        : i % 3 === 1
        ? ApplicationStatus.REJECTED
        : ApplicationStatus.PENDING;

    await prisma.application.create({
      data: {
        talentId: talent.id, // Talent.id is String
        departmentId: department.id, // Department.id is String
        mentorId:
          applicationStatus === ApplicationStatus.ACCEPTED ? mentor.id : null, // Mentor.id is String?
        status: applicationStatus,
        score:
          applicationStatus === ApplicationStatus.ACCEPTED
            ? Math.floor(Math.random() * 50) + 50
            : null,
        feedback:
          applicationStatus === ApplicationStatus.ACCEPTED
            ? "Great potential, looking forward to working with you!"
            : applicationStatus === ApplicationStatus.REJECTED
            ? "Unfortunately, we are unable to offer you a spot at this time."
            : null,
      },
    });

    // If application is accepted, increment mentor's currentStudents
    if (
      applicationStatus === ApplicationStatus.ACCEPTED &&
      mentor.maxStudents !== null // Check if maxStudents exists
    ) {
      await prisma.mentor.update({
        where: { id: mentor.id }, // Use mentor.id (String)
        data: {
          currentStudents: {
            increment: 1,
          },
        },
      });
    }
  }
  console.log("Created applications.");

  // Create Projects for Talents
  for (const talent of talents) {
    const numProjects = Math.floor(Math.random() * 3) + 1; // 1 to 3 projects per talent
    for (let i = 1; i <= numProjects; i++) {
      await prisma.project.create({
        data: {
          talentId: talent.id, // Talent.id is String
          projectName: `Talent ${talent.id}'s Project ${i}`, // Using talent.id
          description: `Description for project ${i} by Talent ${talent.id}.`,
          githubRepo: `github.com/talent${talent.id}/project${i}`,
        },
      });
    }
  }
  console.log("Created projects.");

  // Create Certificates for Talents
  for (const talent of talents) {
    const numCertificates = Math.floor(Math.random() * 2); // 0 to 1 certificates per talent
    for (let i = 1; i <= numCertificates; i++) {
      await prisma.certificate.create({
        data: {
          talentId: talent.id, // Talent.id is String
          title: `Certification in ${
            i % 2 === 0 ? "Full-Stack Web" : "Data Analytics"
          }`,
          fileUrl: `https://example.com/certificates/talent${talent.id}_cert${i}.pdf`,
        },
      });
    }
  }
  console.log("Created certificates.");

  console.log("Seeding finished.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
